profile: cover.short.profile,cover.long.profile
local-prefix: "github.com/k-narusawa/go-app-template"
# threshold:
#   file: 100
#   total: 95
exclude:
  paths:
    - app/main\.go$
    - internal/middleware/.+\.go$
    - internal/repository/.+\.go$
